spring:
  liquibase:
    change-log: "classpath:/db/changelog/changelog-master.xml"
    drop-first: true
  datasource:
    url: jdbc:h2:file:~/bank.db;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

server:
  port: 1337